In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.9954e-42, 0.0000e+00],
        [0.0000e+00, 8.7518e-04, 0.0000e+00]])


In [3]:
x = torch.rand(5,5)
print(x)

tensor([[0.3803, 0.4649, 0.6938, 0.7750, 0.9928],
        [0.3107, 0.9069, 0.9101, 0.7243, 0.0658],
        [0.5695, 0.5108, 0.8617, 0.5322, 0.9297],
        [0.1800, 0.3551, 0.0300, 0.3393, 0.1973],
        [0.8184, 0.1065, 0.5823, 0.6400, 0.1437]])


In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0808, -0.4504,  2.0808],
        [ 1.2403, -0.1230, -2.0749],
        [-0.3088, -0.2215,  0.4880],
        [-0.8959, -1.2203,  0.3197],
        [ 0.0603,  0.5003,  1.2764]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5,3,dtype=torch.double)
print(x + y)

tensor([[1.7764, 1.7507, 1.7568],
        [1.1388, 1.0399, 1.8056],
        [1.2553, 1.7499, 1.5893],
        [1.9393, 1.9098, 1.5617],
        [1.9079, 1.0907, 1.0822]], dtype=torch.float64)
