In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38]])


In [4]:
x = torch.rand(5,5)
print(x)

tensor([[0.0192, 0.7667, 0.3985, 0.0700, 0.7086],
        [0.4930, 0.1559, 0.8632, 0.1260, 0.0789],
        [0.3054, 0.3155, 0.2017, 0.6169, 0.8778],
        [0.1361, 0.0180, 0.5191, 0.8110, 0.9739],
        [0.3564, 0.9427, 0.3953, 0.4219, 0.6535]])


In [5]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2862,  1.3316,  0.8827],
        [ 0.0222, -0.8208, -1.4554],
        [ 1.3245, -0.1724, -0.0406],
        [-0.7552,  0.6235, -0.1784],
        [ 1.9772, -0.2929,  0.4087]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5,3,dtype=torch.double)
print(x + y)
print(torch.add(x,y))
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)
y.add_(x)
print(y)

tensor([[1.2417, 1.9077, 1.9816],
        [1.8958, 1.1328, 1.6861],
        [1.0375, 1.6582, 1.3964],
        [1.8136, 1.3289, 1.4803],
        [1.7259, 1.8762, 1.1562]], dtype=torch.float64)
tensor([[1.2417, 1.9077, 1.9816],
        [1.8958, 1.1328, 1.6861],
        [1.0375, 1.6582, 1.3964],
        [1.8136, 1.3289, 1.4803],
        [1.7259, 1.8762, 1.1562]], dtype=torch.float64)
tensor([[1.2417, 1.9077, 1.9816],
        [1.8958, 1.1328, 1.6861],
        [1.0375, 1.6582, 1.3964],
        [1.8136, 1.3289, 1.4803],
        [1.7259, 1.8762, 1.1562]])
tensor([[1.2417, 1.9077, 1.9816],
        [1.8958, 1.1328, 1.6861],
        [1.0375, 1.6582, 1.3964],
        [1.8136, 1.3289, 1.4803],
        [1.7259, 1.8762, 1.1562]], dtype=torch.float64)


In [13]:
print(x)
print(x[:,1])
print(y[:,1])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1.9077, 1.1328, 1.6582, 1.3289, 1.8762], dtype=torch.float64)


In [14]:
x =torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 只能有一个值的时候使用item

In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9150])
-0.9150121212005615


### --------------numpy and torch

In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


### WTF为什么这里B也跟着变了

In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
import copy

c = copy.deepcopy(a.numpy())
print(c)

[2. 2. 2. 2. 2.]


In [23]:
a.add_(1)
print(a)
print(c)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


In [27]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### cuda 

In [28]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+ y
    print(z)
    print(z.to("cpu", torch.double))

tensor([0.0850], device='cuda:0')
tensor([0.0850], dtype=torch.float64)
